name: New features

on:
  push:
    branches:
      - "feature/*"
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Project Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Compile, Build and Test environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh

    - name: Slack Msg
      # You may pin to the exact commit or the version.
      # uses: megamegax/slack_action@dac54751618fa4934f108b10e2dd3a3a0e4eefa3
      uses: megamegax/slack_action@0.2.2
      with:
        # slack webhook
          webHook: https://hooks.slack.com/services/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
        # channel
          channel: demodevops
        # success|failed|canceled
          job_status: Success
        # message
         message: Success
        # user name
        #user_name: # optional
        # user icon
        # user_icon: # optional
        # actions
        #actions: # optional


